### ISSUE TITLE
__() function conflict

### ISSUE THREAD

**Issue by woodholly** [CleanTalk/smf-antispam#47]
Cleantalk conflicts with other mods using __() function as a wrapper for translation (for example very popular Light-Portal SMF mod).
https://github.com/CleanTalk/smf-antispam/search?q=__%28

This leads to:
```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to __() must be of the type array, string given, called in /var/www/html/Sources/cleantalk/lib/Cleantalk/Common/Firewall/FirewallModule.php on line 220
```
And this = forum down.

**Comment by alexandergull** [comment]
Hello.

Thank you for the request.

Look at this quick fix: https://github.com/CleanTalk/smf-antispam/commit/588883ddb6c5d7884c43472b3e0012c064ee162e

This should help.

There is the link to the FIX branch containing these changes. https://github.com/CleanTalk/smf-antispam/tree/fix

Also, we plan to remove compatibility wrappers for common libs in the future.
